### ISSUE TITLE
HFS: invalid calculation of files size (zero)

### ISSUE THREAD

**Issue by sipx** [LubosD/darling-dmg#12]
Sometimes darling-dmg doesn't correctly report files size inside HFS file system. I think it's an important issue.

Code to reproduce: https://gist.github.com/sipx/4b9b1c9f9157eb1e6aa1
Output: https://gist.github.com/sipx/5601a729df06b06b1889

As you can see darling-dmg reports many files as zero-sized, but it's not correct - when you open this DMG with 7zip, it correctly displays sizes, and you can extract those files as well. 
Screenshot with 7z: https://www.dropbox.com/s/k92ekdkyd732g85/7z_works_fine.png?dl=0

DMG to reproduce (5GB, I'm sorry - the only one I have at the moment):
https://www.dropbox.com/s/tpimco03g3276w1/OS%20X%20Yosemite%2010.10.2%20%28Installer%29.dmg?dl=0 (SHA-1: 9AA37847A20848634C7B15D49D078AC774FB8426, you can download this file from other places if you will google for this SHA-1)

**Comment by LubosD** [comment]
```it->second.file.dataFork.logicalSize``` doesn't report file size, but the size of the data fork. In case of compressed files, the data fork size is zero.

I'll have to fix ```hfs_nativeToStat()```.

**Comment by sipx** [comment]
Hi, Lubus and thanks for getting in touch so fast. Looks you're right.

PS. It seems for me that main-fuse.cpp main-test-dmg main-test-hfs+.cpp should be moved outside darling-dmg folder (as not a part of this great dmg reading lib). Probably as examples. hfs_nativeToStat should be also moved to the lib in this case.

**Comment by LubosD** [comment]
I've just noticed that this is already handled in {{hfs_getattr()}} (look for a comment "Compressed FS support"). You should duplicate the logic in this function and then it should work. Let me know if it does not.

**Comment by sipx** [comment]
Yes, it does work - reports correct file size. But I faced another problem now: extracting a file (with HFS_PERM_OFLAG_COMPRESSED) from this DMG is impossibly slow, even if a file is small. I will report it (with details) to https://github.com/LubosD/darling-dmg/issues/6
