### ISSUE TITLE
CachedReader::nonCachedRead - Illegal range returned by adviseOptimalBlock()

### ISSUE THREAD

**Issue by tomkohen** [LubosD/darling-dmg#14]
When extracting a big (almost 5GB file InstallESD.dmg) cached reader fails with "Illegal range returned by adviseOptimalBlock()" exception.

Looks like these (pos) variables can go out of int32_t boundaries in CachedReader::read:

    // Uncached blocks at the end of the requested range
    const int32_t toRead = done - lastFetchPos;
    const int32_t pos = offset + lastFetchPos;

**Comment by LubosD** [comment]
Hopefully fixed that. Stupid mistake.

**Comment by tomkohen** [comment]
Fixed, thanks!
