### ISSUE TITLE
GUID -> GPT_GUID

### ISSUE THREAD

**Issue by tomkohen** [LubosD/darling-dmg#15]
It's a very small issue, but still. 
When compiling darling-dmg under Windows and Visual C++ compiler, GUID structure is already defined there in Windows SDK headers. So I have to rename to GUID (in gpt.h) into GPT_GUID.

```
struct GPT_GUID
{
	uint32_t data1;
	uint16_t data2, data3;
	uint8_t data4[8];
};

struct GPTPartition
{
	GPT_GUID typeGUID;
	GPT_GUID partitionGUID;
	uint64_t firstLBA, lastLBA;
	uint64_t flags;
	uint16_t name[36];
};
```

Why not to pull this for Windows users? Thanks

**Comment by LubosD** [comment]
I didn't see any pull request for this one, so I fixed it myself.
