### ISSUE TITLE
HFSHighLevelVolume::listDirectory doesn't work correctly with compressed files

### ISSUE THREAD

**Issue by tomkohen** [LubosD/darling-dmg#20]
HFSHighLevelVolume::listDirectory uses hfs_nativeToStat
But hfs_nativeToStat doesn't handle compressed files logic as in HFSHighLevelVolume::stat

PS. Is HFSHighLevelVolume::stat actually used somewhere?

looks like HFSHighLevelVolume::listDirectory must be changed to use HFSHighLevelVolume::stat

**Comment by LubosD** [comment]
Ouch, my bad.

**Comment by LubosD** [comment]
````HFSHighLevelVolume::stat```` is never used directly right now, because FUSE wants to load directory contents at once to reduce going back and forth between userspace and kernel for every individual file.

I will modify ````listDirectory()```` to call ````stat()````.

**Comment by LubosD** [comment]
Please re-test, I just made a very quick fix.

**Comment by kleuter** [comment]
Yes, it works, thanks!
