### ISSUE TITLE
Crash in CacheZone::store

### ISSUE THREAD

**Issue by tomkohen** [LubosD/darling-dmg#22]
Now it crashes when extracting a big HFS partition (15 669 878 784 bytes) out of DMG file (5GB) to raw format

Crash happens on the line std::copy(data, data+bytes, entry.data.begin()); (Access violation while reading memory)

Seems to be a problem of big numbers

my code:
```
const std::vector<PartitionedDisk::Partition>&partitions = partitionedDisk->partitions();

uint64_t totalSize = 0;
for (int i = 0; i < partitions.size(); i++)
   totalSize += partitions[i].size;

for (int i = 0; i < partitions.size(); i++)
{
	const PartitionedDisk::Partition& part = partitions[i];

	partReader = partitionedDisk->readerForPartition(i);

	if (partReader)
		writeReaderToFile(partReader, &file_out);
}
```

**Comment by tomkohen** [comment]
Update: if I change 
int32_t thistime, rd; 
to uint64_t
 i get 
"Short read from backing reader" exception (no crash)

**Comment by LubosD** [comment]
Any chance you could provide the DMG file to me?

**Comment by tomkohen** [comment]
Uploading right away. FYI the crash appeared after recent speed up cache changes.

**Comment by LubosD** [comment]
BTW - what argument values do you see in the crashing function?

**Comment by tomkohen** [comment]
It stays somewhat longer on 39% of overall totalSize, then crashes.
![sshot-2015-04-29- 11-04-36](https://cloud.githubusercontent.com/assets/7878850/7387704/8aff989e-ee5f-11e4-9097-97913763d46b.png)

CacheZone::store(const std::string& vfile, uint64_t blockId, const uint8_t* data, size_t bytes)
vfile = "part-0"
blockId = 1728502
data = 0x498d6040 <Error reading characters of string.> Looks like this pointer is broken!
bytes = 4096

CachedReader::nonCachedRead(void* buf, int32_t count, uint64_t offset):
buf = 0x04e18040
count = 5173248
offset = 6113267712

**Comment by tomkohen** [comment]
Uploading would take ages, here's the torrent file for it
https://www.dropbox.com/s/hwf2zwky5smk67l/OS%20X%20Base%20System.torrent?dl=1
It is the same as I have (checked SHA-1)

**Comment by LubosD** [comment]
My current suspect is this line:
````uint64_t cachePos = (blockStart + (CacheZone::BLOCK_SIZE-1)) & ~(CacheZone::BLOCK_SIZE-1);````
the value being bit-negated (~) should first be cast to uint64_t.

**Comment by kleuter** [comment]
Nope - didn't help

**Comment by tomkohen** [comment]
Nope, didn't help

**Comment by tomkohen** [comment]
It also crashes for another DMG file, about 4.5 GB with a single FAT32 partition

**Comment by LubosD** [comment]
Should be fixed. I also fixed partition detection on that DMG file and enlarged cache zone.

**Comment by tomkohen** [comment]
Thank you! Works now
