### ISSUE TITLE
Some files/folders are skipped from a DMG file

### ISSUE THREAD

**Issue by tomkohen** [LubosD/darling-dmg#23]
Hope you didn't delete the DMG file from #22 

For example:
"System\Library\Frameworks\CoreServices.framework\Versions\A\Frameworks\AE.framework\Versions\A\Resources"
folder is skipped

HFSCatalogBTree::listDirectory :

```
// determine the CNID of the directory
rv = stat(path, &dir);
if (rv != 0) 
    return rv; // returns -2
````

Overall, about 600 MB of files/folders is not extracted from this DMG file.
Also there's "Overflow extents not found for given CNID" exception

**Comment by LubosD** [comment]
I still have the DMG file, I'll figure it out soon. Thank you for the report.

**Comment by LubosD** [comment]
There is a lot more trouble it seems:

````
lubos@zeus ~/.darling/mounts/mount1/System/Library/Frameworks/CoreServices.framework $ ls -l
ls: cannot read symbolic link CoreServices: Invalid argument
ls: cannot read symbolic link Frameworks: Invalid argument
ls: cannot read symbolic link Resources: Invalid argument
total 2
lrwxr-xr-x 1 root root   29 Sep 10  2014 CoreServices
lrwxr-xr-x 1 root root   27 Sep 10  2014 Frameworks
-rw-r--r-- 1 root root 1069 Aug 25  2013 module.map
lrwxr-xr-x 1 root root   26 Sep 10  2014 Resources
drwxr-xr-x 1 root root    0 Sep 10  2014 Versions
````

**Comment by LubosD** [comment]
I've fixed symlink support (regression). The folder you're talking about seems to be accessible.

Could you give me some more examples of problematic files? Especially the extents overflow problem is worrying me.

**Comment by tomkohen** [comment]
Hm. I'm not using main-fuse.cpp and fuse_operations.
Is there a way to fix the darling-dmg library itself? (HFSCatalogBTree::listDirectory)

**Comment by LubosD** [comment]
Well, as far as symlinks are concerned, they are resolved by upper layers (FUSE), hence my code doesn't need to care about them.

But the path "System\Library\Frameworks\CoreServices.framework\Versions\A\Frameworks\AE.framework\Versions\A\Resources" doesn't contain any symlinks. On my system it can be stat'd successfully:

````
lubos@zeus ~/.darling/mounts/mount1/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A $ stat Resources/
  File: ‘Resources/’
  Size: 0               Blocks: 0          IO Block: 512    directory
Device: 20h/32d Inode: 145         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2014-09-18 19:22:11.000000000 +0200
Modify: 2013-08-25 04:59:49.000000000 +0200
Change: 2014-09-10 04:27:48.000000000 +0200
 Birth: -
````

So it's hard to say what your problem is.

**Comment by bpietroiu** [comment]
I have the same Overflow extents not found problem.
I am using your code as a library to extract dmg file on windows.

The DMG I am talking is Xcode 6.3 dmg from Apple. I can give you a link to it and the path to the file having this problem

**Comment by LubosD** [comment]
Please do. Thanks!

**Comment by tomkohen** [comment]
LubosD, 

Try to read the contents of the DMG, it won't ready it all
https://gist.github.com/tomkohen/d979c70f2bd52e1cf9a5
Same for XCode 6.3.2 DMG

**Comment by bpietroiu** [comment]
Here is the DMG link (you need to sign in into developer.apple.com, signup is free)
https://developer.apple.com/downloads/download.action?path=Developer_Tools/Xcode_6.3/Xcode_6.3.dmg

Here is the file that fails in HFSFork.cpp, 
		throw std::exception("Overflow extents not found for given CNID");
 
/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Foundation

**Comment by tomkohen** [comment]
Same thing without sign up: https://www.dropbox.com/s/kjbo4axr8a9pnwv/Xcode_6.3.dmg?dl=1
Same problem

**Comment by LubosD** [comment]
Please try it now.

**Comment by tomkohen** [comment]
Lubus, it doesn't work for me. I've updated my sample code:
https://gist.github.com/tomkohen/d979c70f2bd52e1cf9a5
This simple recursive function fails at some point for both OSX.dmg (5GB) file and XCode DMG
But it's OK for lots of other DMG files. Am I doing something incorrectly?

**Comment by LubosD** [comment]
Last commit only fixed the extents overflow problem. I've tried running a Bash loop to read all files in a mounted filesystem and it looked fine.

Can you give me more examples of problematic paths?

**Comment by tomkohen** [comment]
The original code throws fatal exception when readDirectory fails so I had to modify the code in order to get all cases of skipped folders. Using latest version of darling-dmg.

OSX.dmg - only 2 folders are skipped. Looks like you fixed something!

System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/Resources
System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/Support

When extracting, one file is skipped with file_not_found_error exception in HFSHighLevelVolume::openFile
Full file path: System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE

**Comment by LubosD** [comment]
Umm, accessing both mentioned directories and reading the AE file works just fine for me under Linux (tried both GCC and Clang), so it's going to be pretty difficult to fix :-(

**Comment by tomkohen** [comment]
XCode DMG, skipped folders:
- "Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/irb/lc/ja"
- "Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/share/tokenizer/zh"

**bpietroiu ** do you have the same issue?

**Comment by LubosD** [comment]
When I have time, I'll try running the code under Windows. The only thing that comes to my mind is that ICU could behave differently.

**Comment by tomkohen** [comment]
LubosD, the thing is that I'm not using ICU (replaced it with custom code to remove this dependency).

HFSCatalogBTree::stat for 
-System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/Resources
fails for the last token **Resources**. More specifically **findRecordForParentAndName** returns nullptr
I did some debugging inside **HFSCatalogBTree::findRecordForParentAndName**, I found it that leafNode.recordCount() is 55 and looks like it's not enough.. only the last 54 item has actually the same parent (31), it's **_CodeSignature** folder. Other sub-items Resorces/Support/AE are skipped -> hence the problem

**Comment by tomkohen** [comment]
LubosD, I'm sorry but it turned to be my issue. Your guess was correct, my NoICU helpers implementation has problems (will fix them). Sorry for the troubles
