### ISSUE TITLE
Possible uint32_t overflow in HFSZlibReader

### ISSUE THREAD

**Issue by tomkohen** [LubosD/darling-dmg#27]
The line
```
m_offsets.push_back(std::pair<uint32_t,uint32_t>(0, m_reader->length()));
```
can possibly lead to uint32_t overflow because length() returns uint64_t

**Comment by LubosD** [comment]
It may appear so, but it will never happen. This branch of code is only used for compressed data stored in extended attributes. And these cannot be so long.
I'll add a comment into the code.
