### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by sipx** [LubosD/darling-dmg#6]
Hello,

Compiled your code to test extraction of DMG file on Win7.

The code is really great, but: I did a performance test when extracting a 5GB file from 'OS X 10.10.dmg'. It's 2.5-3 times slower than any other software (7zip) that can simply extract a DMG file.

I used different buffer sizes, from 1kb to 10 MB, the results are almost the same.

Profiler says that all the CPU time goes to BZ2_bzDecompress

Any thoughts?
Thanks

**Comment by sipx** [comment]
Here we go. Extracting a single 1MB file takes *50* seconds (Intel Core i3 3.0 Ghz/Release/x86), during the extraction CPU usage is 100% :disappointed:

Extract test source: https://gist.github.com/sipx/c7d4b83d410cd7b6f2b4
Output:

File: Install OS X Yosemite.app/Contents/PlugIns/IA.bundle/Contents/MacOS/IA
Size: 1001456 bytes
Extract time: *50 seconds*
File: Install OS X Yosemite.app/Contents/PlugIns/IA.bundle/Contents/MacOS/libBaseIA.dylib
Size: 94816 bytes
Extract time: *5 seconds*

PS. Looks like CachedReader doesn't work here.

**Comment by LubosD** [comment]
I'll try to make the cache smarter by introducing Reader::adviseOptimalBlock(). This will be used by CachedReader::read() to always read and cache the whole underlying block.

**Comment by LubosD** [comment]
Done. I didn't have time to look for/download a DMG with compressed files, but I wrote a unit test and everything looked OK.

Please let me know how it works for you now.

**Comment by dufreyne** [comment]
Updated to the latest rev (78ec68d6697ea26020e343e964568c9a5aa60f1f)
extract.cpp test above fails with "Illegal range returned by adviseOptimalBlock()"

**Comment by sipx** [comment]
Updated to the latest rev (3a4dcca6e4dfb4b1a872b6916258d9dea531d25e)
extract.cpp test above fails with "Illegal range returned by adviseOptimalBlock()"
blockStart 28672, offset 24576

**Comment by LubosD** [comment]
I've fixed the exception (locally), but I can confirm that the extraction of 'IA' runs at 19.3 KB/s. I will dig deeper.

**Comment by LubosD** [comment]
OK, finding the issue wasn't too hard. The problem is the whole image is BZ2 compressed and there is no caching placed between DMGPartition and HFSVolume.

**Comment by LubosD** [comment]
I hope I've fixed the problem. Reading now seems to be instant.

BTW: I'm planning on moving all the logic from main-fuse.cpp into a new high-level HFS reading class, so you won't have to duplicate any of the logic from ````hfs_*```` functions any more.

**Comment by sipx** [comment]
Thank you. extract.cpp now works as it should (fast).
But I faced crash in "CacheZone::get" (auto it = m_cache.find(key); line) when extracting the whole "OS X Yosemite 10.10.2 (Installer).dmg". Will look into it to create a reproducible sample

**Comment by sipx** [comment]
The crash was my fault, I had to tune my code in order to match your new caching logic.
